services:
  connect:
    image: debezium/connect:2.7.3.Final
    restart: always
    ports:
      - "8085:8083"
    environment:
      - BOOTSTRAP_SERVERS=91.108.110.44:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_status
      - KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
      - VALUE_CONVERTER_SCHEMAS_ENABLE=false
      - KEY_CONVERTER_SCHEMAS_ENABLE=false
      - CONNECTORS_PLUGIN_PATH=/kafka/connect