version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # phpMyAdmin for MySQL
  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOSTS: mysql,89.116.20.146:33062
      PMA_VERBOSE: "Localhost Server,HCTM Surgery"
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_ARBITRARY: 1
      PHP_UPLOAD_MAX_FILESIZE: 64M
      PHP_MAX_INPUT_VARS: 10000
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

  # PostgreSQL Database
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # pgAdmin for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:6.9
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: 0
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always

volumes:
  mysql_data:
  postgres_data:
