version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

  # phpMyAdmin for MySQL
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always

  # PostgreSQL Database
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  # pgAdmin for PostgreSQL
  pgadmin:
    image: dpage/pgadmin4:6.9
    container_name: pgadmin
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=root@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=0
      - PGADMIN_CONFIG_ALLOW_SAVE_PASSWORD=TRUE
      - TZ=Asia/Jakarta
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: always
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  mysql_data:
  postgres_data:
  pgadmin_data:
