version: "3.8"

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: hctm_surgery
      MYSQL_DATABASE: hctm_surgery
      MYSQL_ROOT_PASSWORD: vEf6sk98f2bcukaPD4nXCraSXstt2zvnWpeomg8LIH0t0t8LJZ
      MYSQL_PASSWORD: vEf6sk98f2bcukaPD4nXCraSXstt2zvnWpeomg8LIH0t0t8LJZ
    ports:
      - "33062:3306"
    volumes:
      - db_data_mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend_surgery_fastapi
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    restart: always
    volumes:
      - backend_uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend_surgery
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    restart: always

volumes:
  db_data_mysql:
  backend_uploads:
