services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.15
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"