services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: tkfnQYTaS5Ltmtmj7daZhuP9oZHH7yJmER5JNcf8MlVrmRxLzO
    ports:
      - "5432:5432"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.tcp.routers.postgres.rule=HostSNI(`postgresql.amanahnurehsan.org`)"
  #     - "traefik.tcp.routers.postgres.entrypoints=postgres"
  #     - "traefik.tcp.routers.postgres.tls=true"
  #     - "traefik.tcp.routers.postgres.tls.certresolver=myresolver"
  #     - "traefik.tcp.services.postgres.loadbalancer.server.port=5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # traefik:
  #   image: traefik:v3.5.2
  #   restart: always
  #   command:
  #     - "--providers.docker=true"
  #     - "--entrypoints.web.address=:80"
  #     - "--entrypoints.websecure.address=:443"
  #     - "--entrypoints.postgres.address=:5432"
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
  #     - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
  #     - "--certificatesresolvers.myresolver.acme.email=rizfankusuma@gmail.com"
  #     - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #     - "5432:5432"
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock:ro"
  #     - "./letsencrypt:/letsencrypt"

volumes:
  postgres_data:
