services:
  redis:
      image: redis:latest
      restart: always
      ports:
        - "6379:6379"
      command: redis-server --appendonly yes --save 60 1 --loglevel warning
      volumes:
        - redis_data:/data

volumes:
  redis_data: