services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./php-app:/var/www/html

  web:
    image: nginx:stable
    restart: always
    ports:
      - "8009:80"
    volumes:
      - ./php-app:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app